// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Source: CHANGELOG.md latest "## Version X.Y.Z" heading.
export const RIOKO_VERSION = "8.4.0";
export const RIOKO_STABLE_BUILD = true;
