#!/usr/bin/env node
// Reads the latest version + date from ../CHANGELOG.md and writes
// src/lib/version.ts. Runs as predev/prebuild so the dashboard footer
// always reflects the changelog head.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const changelogPath = resolve(here, "..", "..", "CHANGELOG.md");
const outPath = resolve(here, "..", "src", "lib", "version.ts");

const md = readFileSync(changelogPath, "utf8");

// First header line is the latest entry, e.g.
// "## 💎 Version 6.1.0 — Landing Redesign & Brand System — May 18, 2026"
const m = md.match(/^##\s.*?Version\s+([\d.]+)/m);
if (!m) {
  console.error("[sync-version] could not parse version from CHANGELOG.md");
  process.exit(1);
}
const version = m[1];

// stableBuild = true unless the version line contains "-rc", "-beta", "-alpha"
const stableBuild = !/-(rc|beta|alpha|preview)/i.test(md.split("\n")[0] ?? "");

const out = `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Source: CHANGELOG.md latest "## Version X.Y.Z" heading.
export const RIOKO_VERSION = ${JSON.stringify(version)};
export const RIOKO_STABLE_BUILD = ${stableBuild};
`;

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, out, "utf8");
console.log(`[sync-version] wrote v${version} (stable=${stableBuild}) -> ${outPath}`);
