#!/usr/bin/env node
// Reads ../../CHANGELOG.md and writes two generated files:
//
//   src/lib/version.ts             the head version + stable flag (footer badge)
//   src/lib/changelog.generated.ts every entry, parsed (the /changelog page)
//
// Runs as predev/prebuild, so both always reflect the changelog. The page
// cannot read the file itself: it renders on the edge runtime, where there is
// no fs, so the markdown has to become a module at build time.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse, changelogPath } from "./changelog-parse.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const libDir = resolve(here, "..", "src", "lib");

const entries = parse(readFileSync(changelogPath, "utf8"));
if (entries.length === 0) {
    console.error("[sync-version] could not parse any version from CHANGELOG.md");
    process.exit(1);
}

const head = entries[0];
const version = head.version;
// A pre-release label on the head entry marks the build as preview.
const stableBuild = !/-(rc|beta|alpha|preview)/i.test(`${version} ${head.title}`);

mkdirSync(libDir, { recursive: true });

writeFileSync(
    resolve(libDir, "version.ts"),
    `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Source: CHANGELOG.md latest "## Version X.Y.Z" heading.
export const RIOKO_VERSION = ${JSON.stringify(version)};
export const RIOKO_STABLE_BUILD = ${stableBuild};
`,
    "utf8",
);

writeFileSync(
    resolve(libDir, "changelog.generated.ts"),
    `// AUTO-GENERATED by scripts/sync-version.mjs — do not edit by hand.
// Source: CHANGELOG.md. Edit the changelog, not this file.

export type ChangelogBlock = { t: "h" | "li" | "p" | "code"; text: string };

export type ChangelogEntry = {
    version: string;
    emoji: string;
    title: string;
    /** As written in the changelog, e.g. "September 12, 2026". */
    date: string;
    /** Last commit included in the release, when the entry records one. */
    commit: string;
    /** The entry opens with a **Destaque** paragraph. */
    highlight: boolean;
    body: ChangelogBlock[];
    /** The "Para o comerciante" bullets, empty when the release is silent. */
    publicBody: ChangelogBlock[];
};

export const CHANGELOG: ChangelogEntry[] = ${JSON.stringify(entries, null, 4)};

/** What a merchant sees: only the releases that said something to them. */
export const CHANGELOG_PUBLIC: ChangelogEntry[] = CHANGELOG.filter(
    (e) => e.publicBody.length > 0,
);
`,
    "utf8",
);

console.log(
    `[sync-version] v${version} (stable=${stableBuild}), ${entries.length} changelog entries -> src/lib/`,
);
