// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetV2AuthCheckData, GetV2AuthCheckErrors, GetV2AuthCheckResponses, GetV2DocumentsByIdData, GetV2DocumentsByIdErrors, GetV2DocumentsByIdLinkData, GetV2DocumentsByIdLinkErrors, GetV2DocumentsByIdLinkResponses, GetV2DocumentsByIdRelatedData, GetV2DocumentsByIdRelatedErrors, GetV2DocumentsByIdRelatedResponses, GetV2DocumentsByIdResponses, GetV2InvoiceReceiptsByIdData, GetV2InvoiceReceiptsByIdErrors, GetV2InvoiceReceiptsByIdResponses, GetV2InvoicesByIdData, GetV2InvoicesByIdErrors, GetV2InvoicesByIdResponses, GetV2MetaErrorCodesData, GetV2MetaErrorCodesResponses, GetV2TaxesData, GetV2TaxesErrors, GetV2TaxesResponses, PostV2ChangeStateData, PostV2ChangeStateErrors, PostV2ChangeStateResponses, PostV2CreditNotesData, PostV2CreditNotesErrors, PostV2CreditNotesResponses, PostV2DocumentsByIdEmailData, PostV2DocumentsByIdEmailErrors, PostV2DocumentsByIdEmailResponses, PostV2DocumentsData, PostV2DocumentsErrors, PostV2DocumentsReferenceData, PostV2DocumentsReferenceErrors, PostV2DocumentsReferenceResponses, PostV2DocumentsResponses, PostV2InvoiceReceiptsData, PostV2InvoiceReceiptsErrors, PostV2InvoiceReceiptsResponses, PostV2InvoicesData, PostV2InvoicesErrors, PostV2InvoicesResponses, PutV2CreditNotesByIdData, PutV2CreditNotesByIdErrors, PutV2CreditNotesByIdResponses, PutV2DocumentsByIdData, PutV2DocumentsByIdErrors, PutV2DocumentsByIdResponses, PutV2InvoiceReceiptsByIdData, PutV2InvoiceReceiptsByIdErrors, PutV2InvoiceReceiptsByIdResponses, PutV2InvoicesByIdData, PutV2InvoicesByIdErrors, PutV2InvoicesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new IxApi()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class ById extends HeyApiClient {
    /**
     * Get invoice by Id
     */
    public get<ThrowOnError extends boolean = false>(options: Options<GetV2InvoicesByIdData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetV2InvoicesByIdResponses, GetV2InvoicesByIdErrors, ThrowOnError>({ url: '/v2/invoices/{id}', ...options });
    }
    
    /**
     * Update invoice
     */
    public put<ThrowOnError extends boolean = false>(options: Options<PutV2InvoicesByIdData, ThrowOnError>) {
        return (options.client ?? this.client).put<PutV2InvoicesByIdResponses, PutV2InvoicesByIdErrors, ThrowOnError>({
            url: '/v2/invoices/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Invoices extends HeyApiClient {
    /**
     * Create invoice
     */
    public post<ThrowOnError extends boolean = false>(options: Options<PostV2InvoicesData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostV2InvoicesResponses, PostV2InvoicesErrors, ThrowOnError>({
            url: '/v2/invoices',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    private _byId?: ById;
    get byId(): ById {
        return this._byId ??= new ById({ client: this.client });
    }
}

export class ById2 extends HeyApiClient {
    /**
     * Get invoice receipt by Id
     */
    public get<ThrowOnError extends boolean = false>(options: Options<GetV2InvoiceReceiptsByIdData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetV2InvoiceReceiptsByIdResponses, GetV2InvoiceReceiptsByIdErrors, ThrowOnError>({ url: '/v2/invoice_receipts/{id}', ...options });
    }
    
    /**
     * Update invoice receipt
     */
    public put<ThrowOnError extends boolean = false>(options: Options<PutV2InvoiceReceiptsByIdData, ThrowOnError>) {
        return (options.client ?? this.client).put<PutV2InvoiceReceiptsByIdResponses, PutV2InvoiceReceiptsByIdErrors, ThrowOnError>({
            url: '/v2/invoice_receipts/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class InvoiceReceipts extends HeyApiClient {
    /**
     * Create invoice receipt
     */
    public post<ThrowOnError extends boolean = false>(options: Options<PostV2InvoiceReceiptsData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostV2InvoiceReceiptsResponses, PostV2InvoiceReceiptsErrors, ThrowOnError>({
            url: '/v2/invoice_receipts',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    private _byId?: ById2;
    get byId(): ById2 {
        return this._byId ??= new ById2({ client: this.client });
    }
}

export class ById3 extends HeyApiClient {
    /**
     * Update credit note
     */
    public put<ThrowOnError extends boolean = false>(options: Options<PutV2CreditNotesByIdData, ThrowOnError>) {
        return (options.client ?? this.client).put<PutV2CreditNotesByIdResponses, PutV2CreditNotesByIdErrors, ThrowOnError>({
            url: '/v2/credit_notes/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class CreditNotes extends HeyApiClient {
    /**
     * Create credit note
     */
    public post<ThrowOnError extends boolean = false>(options: Options<PostV2CreditNotesData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostV2CreditNotesResponses, PostV2CreditNotesErrors, ThrowOnError>({
            url: '/v2/credit_notes',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    private _byId?: ById3;
    get byId(): ById3 {
        return this._byId ??= new ById3({ client: this.client });
    }
}

export class Related extends HeyApiClient {
    /**
     * Get related documents of document
     */
    public get<ThrowOnError extends boolean = false>(options: Options<GetV2DocumentsByIdRelatedData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetV2DocumentsByIdRelatedResponses, GetV2DocumentsByIdRelatedErrors, ThrowOnError>({ url: '/v2/documents/{id}/related', ...options });
    }
}

export class Link extends HeyApiClient {
    /**
     * Get document link
     */
    public get<ThrowOnError extends boolean = false>(options: Options<GetV2DocumentsByIdLinkData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetV2DocumentsByIdLinkResponses, GetV2DocumentsByIdLinkErrors, ThrowOnError>({ url: '/v2/documents/{id}/link', ...options });
    }
}

export class Email extends HeyApiClient {
    /**
     * Send document by email
     */
    public post<ThrowOnError extends boolean = false>(options: Options<PostV2DocumentsByIdEmailData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostV2DocumentsByIdEmailResponses, PostV2DocumentsByIdEmailErrors, ThrowOnError>({
            url: '/v2/documents/{id}/email',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class ById4 extends HeyApiClient {
    /**
     * Get document (invoice, invoice receipt, or credit note)
     */
    public get<ThrowOnError extends boolean = false>(options: Options<GetV2DocumentsByIdData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetV2DocumentsByIdResponses, GetV2DocumentsByIdErrors, ThrowOnError>({ url: '/v2/documents/{id}', ...options });
    }
    
    /**
     * Update document (invoice, invoice receipt, or credit note)
     */
    public put<ThrowOnError extends boolean = false>(options: Options<PutV2DocumentsByIdData, ThrowOnError>) {
        return (options.client ?? this.client).put<PutV2DocumentsByIdResponses, PutV2DocumentsByIdErrors, ThrowOnError>({
            url: '/v2/documents/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    private _related?: Related;
    get related(): Related {
        return this._related ??= new Related({ client: this.client });
    }
    
    private _link?: Link;
    get link(): Link {
        return this._link ??= new Link({ client: this.client });
    }
    
    private _email?: Email;
    get email(): Email {
        return this._email ??= new Email({ client: this.client });
    }
}

export class Reference extends HeyApiClient {
    /**
     * Find document by reference
     *
     * Search for a document across all types (invoice, invoice_receipt, credit_note) by reference number. Searches through all pages until found.
     */
    public post<ThrowOnError extends boolean = false>(options: Options<PostV2DocumentsReferenceData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostV2DocumentsReferenceResponses, PostV2DocumentsReferenceErrors, ThrowOnError>({
            url: '/v2/documents/reference',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class Documents extends HeyApiClient {
    /**
     * Create document (invoice, invoice receipt, or credit note)
     */
    public post<ThrowOnError extends boolean = false>(options: Options<PostV2DocumentsData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostV2DocumentsResponses, PostV2DocumentsErrors, ThrowOnError>({
            url: '/v2/documents',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    private _byId?: ById4;
    get byId(): ById4 {
        return this._byId ??= new ById4({ client: this.client });
    }
    
    private _reference?: Reference;
    get reference(): Reference {
        return this._reference ??= new Reference({ client: this.client });
    }
}

export class Taxes extends HeyApiClient {
    /**
     * List taxes
     */
    public get<ThrowOnError extends boolean = false>(options: Options<GetV2TaxesData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetV2TaxesResponses, GetV2TaxesErrors, ThrowOnError>({ url: '/v2/taxes', ...options });
    }
}

export class Check extends HeyApiClient {
    /**
     * Check InvoiceXpress credentials
     */
    public get<ThrowOnError extends boolean = false>(options: Options<GetV2AuthCheckData, ThrowOnError>) {
        return (options.client ?? this.client).get<GetV2AuthCheckResponses, GetV2AuthCheckErrors, ThrowOnError>({ url: '/v2/auth/check', ...options });
    }
}

export class Auth extends HeyApiClient {
    private _check?: Check;
    get check(): Check {
        return this._check ??= new Check({ client: this.client });
    }
}

export class ChangeState extends HeyApiClient {
    /**
     * Change document state
     */
    public post<ThrowOnError extends boolean = false>(options: Options<PostV2ChangeStateData, ThrowOnError>) {
        return (options.client ?? this.client).post<PostV2ChangeStateResponses, PostV2ChangeStateErrors, ThrowOnError>({
            url: '/v2/change_state',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class ErrorCodes extends HeyApiClient {
    /**
     * List known IX error codes
     *
     * Known IX error codes.
     *
     * Format:
     * - `CODE` - message (optional description)
     *
     * - `API001` - Invalid API key — Happens when passed api key is not valid. Please try to re-invalidate current one and try again
     * - `DOC001` - Document already paid. Cannot be edited — Happens when document (invoice) already finalized, but you try to modify it. Consider removing payments from invoice, or just create new one and edit it.
     * - `DOC002` - Duplicate item in Invoice. — Happens when item has ID and you try to create new Invoice with item which is already created. (a bit stupid error)
     * - `DOC003` - Unknown property was passed. — Happens when unknown property (attribute) was passed to Invoice.
     * - `DOC004` - Country of client was not found.
     * - `DOC005` - You tried to create a client with a code that is already being used — Code is that customisable id that we can assign to a client and use it as a identifier
     * - `DOC006` - You tried to create a client with a name that is already being used
     * - `FAILED` - Request failed
     * - `NOT_FOUND` - Not Found
     * - `PARSE_FAILED` - Failed to parse response
     * - `PLAN001` - This option is not available on current user plan. — Happens when user plan not includes specific option/feature, such as sending emails to customers
     * - `PLAN002` - You have reached the document creation limit for the current period. — You have reached the document creation limit for the current period. Please upgrade your plan to create more documents.
     * - `TAX001` - Invoice missing tax exemption reason
     * - `TAX002` - Tax exemption reason is not needed for Invoice, as it has no items with 0% VAT
     * - `TIMED_OUT` - Request timed out
     * - `UNAUTHORIZED` - Unauthorized
     */
    public get<ThrowOnError extends boolean = false>(options?: Options<GetV2MetaErrorCodesData, ThrowOnError>) {
        return (options?.client ?? this.client).get<GetV2MetaErrorCodesResponses, unknown, ThrowOnError>({ url: '/v2/meta/error-codes', ...options });
    }
}

export class Meta extends HeyApiClient {
    private _errorCodes?: ErrorCodes;
    get errorCodes(): ErrorCodes {
        return this._errorCodes ??= new ErrorCodes({ client: this.client });
    }
}

export class V2 extends HeyApiClient {
    private _invoices?: Invoices;
    get invoices(): Invoices {
        return this._invoices ??= new Invoices({ client: this.client });
    }
    
    private _invoiceReceipts?: InvoiceReceipts;
    get invoiceReceipts(): InvoiceReceipts {
        return this._invoiceReceipts ??= new InvoiceReceipts({ client: this.client });
    }
    
    private _creditNotes?: CreditNotes;
    get creditNotes(): CreditNotes {
        return this._creditNotes ??= new CreditNotes({ client: this.client });
    }
    
    private _documents?: Documents;
    get documents(): Documents {
        return this._documents ??= new Documents({ client: this.client });
    }
    
    private _taxes?: Taxes;
    get taxes(): Taxes {
        return this._taxes ??= new Taxes({ client: this.client });
    }
    
    private _auth?: Auth;
    get auth(): Auth {
        return this._auth ??= new Auth({ client: this.client });
    }
    
    private _changeState?: ChangeState;
    get changeState(): ChangeState {
        return this._changeState ??= new ChangeState({ client: this.client });
    }
    
    private _meta?: Meta;
    get meta(): Meta {
        return this._meta ??= new Meta({ client: this.client });
    }
}

export class IxApi extends HeyApiClient {
    public static readonly __registry = new HeyApiRegistry<IxApi>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        IxApi.__registry.set(this, args?.key);
    }
    
    private _v2?: V2;
    get v2(): V2 {
        return this._v2 ??= new V2({ client: this.client });
    }
}
