// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://ix-proxy.kapta.app' | (string & {});
};

export type GetV2InvoicesByIdData = {
    body?: never;
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/v2/invoices/{id}';
};

export type GetV2InvoicesByIdErrors = {
    /**
     * Response
     */
    400: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2InvoicesByIdError = GetV2InvoicesByIdErrors[keyof GetV2InvoicesByIdErrors];

export type GetV2InvoicesByIdResponses = {
    /**
     * Response
     */
    200: {
        data: {
            invoice: {
                id: number;
                status: string;
                archived: boolean;
                type: string;
                sequence_number: string;
                atcud: string;
                date: string;
                due_date: string;
                reference: string;
                observations: unknown;
                retention: unknown;
                permalink: string;
                sum: number;
                discount: number;
                before_taxes: number;
                taxes: number;
                total: number;
                currency: string;
                client: {
                    id?: number;
                    name?: string;
                    email?: string;
                    country?: string;
                    code?: string;
                    fiscal_id?: string;
                };
                items: Array<{
                    name: string;
                    description: string;
                    unit_price: string;
                    unit: unknown;
                    quantity: string;
                    tax: {
                        id: number;
                        name: string;
                        value: number;
                    };
                    discount?: number;
                    subtotal?: number;
                    tax_amount?: number;
                    discount_amount?: number;
                    total: number;
                }>;
            };
        };
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2InvoicesByIdResponse = GetV2InvoicesByIdResponses[keyof GetV2InvoicesByIdResponses];

export type PutV2InvoicesByIdData = {
    body?: {
        invoice: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
        };
    };
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path: {
        id: number;
    };
    query?: {
        /**
         * Comma-separated resolvers. Supported values: on_tax_fallback_search_tax_by_value
         */
        resolvers?: string;
    };
    url: '/v2/invoices/{id}';
};

export type PutV2InvoicesByIdErrors = {
    /**
     * Validation Error
     */
    400: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PutV2InvoicesByIdError = PutV2InvoicesByIdErrors[keyof PutV2InvoicesByIdErrors];

export type PutV2InvoicesByIdResponses = {
    /**
     * Response
     */
    200: {
        data: {
            id: number;
        };
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PutV2InvoicesByIdResponse = PutV2InvoicesByIdResponses[keyof PutV2InvoicesByIdResponses];

export type PostV2InvoicesData = {
    body?: {
        invoice: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
        };
    };
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path?: never;
    query?: {
        /**
         * Comma-separated resolvers. Supported values: on_tax_fallback_search_tax_by_value
         */
        resolvers?: string;
    };
    url: '/v2/invoices';
};

export type PostV2InvoicesErrors = {
    /**
     * Validation Error
     */
    400: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2InvoicesError = PostV2InvoicesErrors[keyof PostV2InvoicesErrors];

export type PostV2InvoicesResponses = {
    /**
     * Response
     */
    200: {
        data: {
            invoice: {
                id: number;
                status: string;
                archived: boolean;
                type: string;
                sequence_number: string;
                atcud: string;
                date: string;
                due_date: string;
                reference: string;
                observations: unknown;
                retention: unknown;
                permalink: string;
                sum: number;
                discount: number;
                before_taxes: number;
                taxes: number;
                total: number;
                currency: string;
                client: {
                    id: number;
                    name: string;
                    email: string;
                    country: string;
                    code: string;
                    fiscal_id: string;
                };
                items: Array<{
                    name: string;
                    description: string;
                    unit_price: string;
                    unit: unknown;
                    quantity: string;
                    tax: {
                        id: number;
                        name: string;
                        value: number;
                    };
                    discount: number;
                    subtotal: number;
                    tax_amount: number;
                    discount_amount: number;
                    total: number;
                }>;
            };
        };
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2InvoicesResponse = PostV2InvoicesResponses[keyof PostV2InvoicesResponses];

export type GetV2InvoiceReceiptsByIdData = {
    body?: never;
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/v2/invoice_receipts/{id}';
};

export type GetV2InvoiceReceiptsByIdErrors = {
    /**
     * Response
     */
    400: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2InvoiceReceiptsByIdError = GetV2InvoiceReceiptsByIdErrors[keyof GetV2InvoiceReceiptsByIdErrors];

export type GetV2InvoiceReceiptsByIdResponses = {
    /**
     * Response
     */
    200: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2InvoiceReceiptsByIdResponse = GetV2InvoiceReceiptsByIdResponses[keyof GetV2InvoiceReceiptsByIdResponses];

export type PutV2InvoiceReceiptsByIdData = {
    body?: {
        invoice_receipt: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
        };
    };
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path: {
        id: number;
    };
    query?: {
        /**
         * Comma-separated resolvers. Supported values: on_tax_fallback_search_tax_by_value
         */
        resolvers?: string;
    };
    url: '/v2/invoice_receipts/{id}';
};

export type PutV2InvoiceReceiptsByIdErrors = {
    /**
     * Validation Error
     */
    400: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PutV2InvoiceReceiptsByIdError = PutV2InvoiceReceiptsByIdErrors[keyof PutV2InvoiceReceiptsByIdErrors];

export type PutV2InvoiceReceiptsByIdResponses = {
    /**
     * Response
     */
    200: {
        data: {
            id: number;
        };
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PutV2InvoiceReceiptsByIdResponse = PutV2InvoiceReceiptsByIdResponses[keyof PutV2InvoiceReceiptsByIdResponses];

export type PostV2InvoiceReceiptsData = {
    body?: {
        invoice_receipt: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
        };
    };
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path?: never;
    query?: {
        /**
         * Comma-separated resolvers. Supported values: on_tax_fallback_search_tax_by_value
         */
        resolvers?: string;
    };
    url: '/v2/invoice_receipts';
};

export type PostV2InvoiceReceiptsErrors = {
    /**
     * Response
     */
    400: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2InvoiceReceiptsError = PostV2InvoiceReceiptsErrors[keyof PostV2InvoiceReceiptsErrors];

export type PostV2InvoiceReceiptsResponses = {
    /**
     * Response
     */
    200: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2InvoiceReceiptsResponse = PostV2InvoiceReceiptsResponses[keyof PostV2InvoiceReceiptsResponses];

export type PostV2CreditNotesData = {
    body?: {
        credit_note: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
            owner_invoice_id: number;
        };
    };
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path?: never;
    query?: {
        /**
         * Comma-separated resolvers. Supported values: on_tax_fallback_search_tax_by_value
         */
        resolvers?: string;
    };
    url: '/v2/credit_notes';
};

export type PostV2CreditNotesErrors = {
    /**
     * Response
     */
    400: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2CreditNotesError = PostV2CreditNotesErrors[keyof PostV2CreditNotesErrors];

export type PostV2CreditNotesResponses = {
    /**
     * Response
     */
    200: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2CreditNotesResponse = PostV2CreditNotesResponses[keyof PostV2CreditNotesResponses];

export type PutV2CreditNotesByIdData = {
    body?: {
        credit_note: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
            owner_invoice_id: number;
        };
    };
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path: {
        id: number;
    };
    query?: {
        /**
         * Comma-separated resolvers. Supported values: on_tax_fallback_search_tax_by_value
         */
        resolvers?: string;
    };
    url: '/v2/credit_notes/{id}';
};

export type PutV2CreditNotesByIdErrors = {
    /**
     * Validation Error
     */
    400: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PutV2CreditNotesByIdError = PutV2CreditNotesByIdErrors[keyof PutV2CreditNotesByIdErrors];

export type PutV2CreditNotesByIdResponses = {
    /**
     * Response
     */
    200: {
        data: {
            id: number;
        };
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PutV2CreditNotesByIdResponse = PutV2CreditNotesByIdResponses[keyof PutV2CreditNotesByIdResponses];

export type GetV2DocumentsByIdData = {
    body?: never;
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path: {
        id: number;
    };
    query?: {
        /**
         * Optional document type. If omitted, the API will try invoice, invoice_receipt, then credit_note
         */
        type?: 'invoice' | 'invoice_receipt' | 'credit_note';
    };
    url: '/v2/documents/{id}';
};

export type GetV2DocumentsByIdErrors = {
    /**
     * Response
     */
    400: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2DocumentsByIdError = GetV2DocumentsByIdErrors[keyof GetV2DocumentsByIdErrors];

export type GetV2DocumentsByIdResponses = {
    /**
     * Response
     */
    200: {
        data: {
            id: number;
            status: string;
            archived: boolean;
            type: string;
            tax_exemption?: string;
            sequence_number: string;
            atcud: string;
            date: string;
            due_date: string;
            reference: string;
            observations: unknown;
            retention: unknown;
            permalink: string;
            sum: number;
            discount: number;
            before_taxes: number;
            taxes: number;
            total: number;
            currency: string;
            client: {
                id: number;
                name: string;
                email: string;
                country: string;
                code: string;
                fiscal_id?: string;
            };
            items: Array<{
                name: string;
                description: string;
                unit_price: string;
                unit: unknown;
                quantity: string;
                tax: {
                    id: number;
                    name: string;
                    value: number;
                };
                discount: number;
                subtotal: number;
                tax_amount: number;
                discount_amount: number;
                total: number;
            }>;
        } | {
            id: number;
            status: string;
            archived: boolean;
            type: string;
            tax_exemption?: string;
            sequence_number: string;
            atcud: string;
            date: string;
            due_date: string;
            reference: string;
            observations: unknown;
            retention: unknown;
            permalink: string;
            sum: number;
            discount: number;
            before_taxes: number;
            taxes: number;
            total: number;
            currency: string;
            client: {
                id: number;
                name: string;
                email: string;
                country: string;
                code: string;
                fiscal_id?: string;
            };
            items: Array<{
                name: string;
                description: string;
                unit_price: string;
                unit: unknown;
                quantity: string;
                tax: {
                    id: number;
                    name: string;
                    value: number;
                };
                discount: number;
                subtotal: number;
                tax_amount: number;
                discount_amount: number;
                total: number;
            }>;
            owner_invoice_id?: number;
        };
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2DocumentsByIdResponse = GetV2DocumentsByIdResponses[keyof GetV2DocumentsByIdResponses];

export type PutV2DocumentsByIdData = {
    body?: {
        type: 'invoice';
        data: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
        };
    } | {
        type: 'invoice_receipt';
        data: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
        };
    } | {
        type: 'credit_note';
        data: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
            owner_invoice_id: number;
        };
    };
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path: {
        id: number;
    };
    query?: {
        /**
         * Comma-separated resolvers. Supported values: on_tax_fallback_search_tax_by_value
         */
        resolvers?: string;
    };
    url: '/v2/documents/{id}';
};

export type PutV2DocumentsByIdErrors = {
    /**
     * Validation Error
     */
    400: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PutV2DocumentsByIdError = PutV2DocumentsByIdErrors[keyof PutV2DocumentsByIdErrors];

export type PutV2DocumentsByIdResponses = {
    /**
     * Response
     */
    200: {
        data: {
            id: number;
        };
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PutV2DocumentsByIdResponse = PutV2DocumentsByIdResponses[keyof PutV2DocumentsByIdResponses];

export type PostV2DocumentsData = {
    body?: {
        type: 'invoice';
        data: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
        };
    } | {
        type: 'invoice_receipt';
        data: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
        };
    } | {
        type: 'credit_note';
        data: {
            date: string | string;
            due_date: string | string;
            tax_exemption_reason?: string;
            client: {
                id?: number;
                name?: string;
                email?: string;
                fiscal_id?: string;
                address?: string;
                postal_code?: string;
                country?: string;
                code?: string | null;
                city?: string;
                phone?: string;
            };
            observations?: string;
            items: Array<{
                quantity: number;
                id?: number;
                name?: string;
                code?: string;
                description?: string;
                tax: {
                    id?: number;
                    name: string;
                    value: number;
                } | number;
                unit_price: number;
                rrp?: number;
                unit?: string | null;
                retention?: number;
                discount?: number;
                discount_amount?: number;
                subtotal?: number;
                tax_amount?: number;
                total?: number;
            }>;
            global_discount?: {
                value_type: 'percentage' | 'absolute';
                value: number;
            };
            reference?: string;
            retention?: string;
            manual_sequence_number?: string;
            owner_invoice_id: number;
        };
    };
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path?: never;
    query?: {
        /**
         * Comma-separated resolvers. Supported values: on_tax_fallback_search_tax_by_value
         */
        resolvers?: string;
    };
    url: '/v2/documents';
};

export type PostV2DocumentsErrors = {
    /**
     * Validation Error
     */
    400: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2DocumentsError = PostV2DocumentsErrors[keyof PostV2DocumentsErrors];

export type PostV2DocumentsResponses = {
    /**
     * Response
     */
    200: {
        data: {
            id: number;
            status: string;
            archived: boolean;
            type: string;
            sequence_number: string;
            atcud: string;
            date: string;
            due_date: string;
            reference: string;
            observations: unknown;
            retention: unknown;
            permalink: string;
            sum: number;
            discount: number;
            before_taxes: number;
            taxes: number;
            total: number;
            currency: string;
            client: {
                id: number;
                name: string;
                email: string;
                country: string;
                code: string;
                fiscal_id?: string;
            };
            items: Array<{
                name: string;
                description: string;
                unit_price: string;
                unit: unknown;
                quantity: string;
                tax: {
                    id: number;
                    name: string;
                    value: number;
                };
                discount: number;
                subtotal: number;
                tax_amount: number;
                discount_amount: number;
                total: number;
            }>;
        } | {
            id: number;
            status: string;
            archived: boolean;
            type: string;
            sequence_number: string;
            atcud: string;
            date: string;
            due_date: string;
            reference: string;
            observations: unknown;
            retention: unknown;
            permalink: string;
            sum: number;
            discount: number;
            before_taxes: number;
            taxes: number;
            total: number;
            currency: string;
            client: {
                id: number;
                name: string;
                email: string;
                country: string;
                code: string;
                fiscal_id?: string;
            };
            items: Array<{
                name: string;
                description: string;
                unit_price: string;
                unit: unknown;
                quantity: string;
                tax: {
                    id: number;
                    name: string;
                    value: number;
                };
                discount: number;
                subtotal: number;
                tax_amount: number;
                discount_amount: number;
                total: number;
            }>;
            owner_invoice_id?: number;
        };
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2DocumentsResponse = PostV2DocumentsResponses[keyof PostV2DocumentsResponses];

export type GetV2DocumentsByIdRelatedData = {
    body?: never;
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path: {
        id: number;
    };
    query?: never;
    url: '/v2/documents/{id}/related';
};

export type GetV2DocumentsByIdRelatedErrors = {
    /**
     * Response
     */
    400: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2DocumentsByIdRelatedError = GetV2DocumentsByIdRelatedErrors[keyof GetV2DocumentsByIdRelatedErrors];

export type GetV2DocumentsByIdRelatedResponses = {
    /**
     * Response
     */
    200: {
        data: {
            documents: Array<{
                id: number;
                status: string;
                archived: boolean;
                type: string;
                sequence_number: string;
                atcud: string;
                date: string;
                due_date: string;
                reference: string;
                observations: unknown;
                retention: unknown;
                permalink: string;
                sum: number;
                discount: number;
                before_taxes: number;
                taxes: number;
                total: number;
                currency: string;
                client: {
                    id?: number;
                    name?: string;
                    email?: string;
                    country?: string;
                    code?: string;
                    fiscal_id?: string;
                };
                items: Array<{
                    name: string;
                    description: string;
                    unit_price: string;
                    unit: string | null;
                    quantity: string;
                    tax: {
                        id: number;
                        name: string;
                        value: number;
                    };
                    discount?: number;
                    subtotal?: number;
                    tax_amount?: number;
                    discount_amount?: number;
                    total: number;
                }>;
            }>;
        };
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2DocumentsByIdRelatedResponse = GetV2DocumentsByIdRelatedResponses[keyof GetV2DocumentsByIdRelatedResponses];

export type GetV2DocumentsByIdLinkData = {
    body?: never;
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path: {
        id: number;
    };
    query: {
        /**
         * Type of link returned. `permalink` returns permalink of invoice, `dashboard` returns link to invoice in dashboard
         */
        type: 'permalink' | 'dashboard';
    };
    url: '/v2/documents/{id}/link';
};

export type GetV2DocumentsByIdLinkErrors = {
    /**
     * Response
     */
    400: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2DocumentsByIdLinkError = GetV2DocumentsByIdLinkErrors[keyof GetV2DocumentsByIdLinkErrors];

export type GetV2DocumentsByIdLinkResponses = {
    /**
     * Response
     */
    200: {
        data: string;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2DocumentsByIdLinkResponse = GetV2DocumentsByIdLinkResponses[keyof GetV2DocumentsByIdLinkResponses];

export type PostV2DocumentsByIdEmailData = {
    body?: {
        message: {
            client: {
                email: string;
                save?: '0' | '1';
            };
            subject?: string;
            body?: string;
            cc?: string;
            bcc?: string;
        };
    };
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path: {
        id: number;
    };
    query?: {
        /**
         * Optional document type (collection). If omitted, the API will try invoices, invoice_receipts, then credit_notes
         */
        type?: 'invoices' | 'invoice_receipts' | 'credit_notes';
    };
    url: '/v2/documents/{id}/email';
};

export type PostV2DocumentsByIdEmailErrors = {
    /**
     * Response
     */
    400: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2DocumentsByIdEmailError = PostV2DocumentsByIdEmailErrors[keyof PostV2DocumentsByIdEmailErrors];

export type PostV2DocumentsByIdEmailResponses = {
    /**
     * Response
     */
    200: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2DocumentsByIdEmailResponse = PostV2DocumentsByIdEmailResponses[keyof PostV2DocumentsByIdEmailResponses];

export type PostV2DocumentsReferenceData = {
    body?: {
        /**
         * The reference number to search for
         */
        reference: string;
    };
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path?: never;
    query?: never;
    url: '/v2/documents/reference';
};

export type PostV2DocumentsReferenceErrors = {
    /**
     * Unauthorized
     */
    401: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
    /**
     * Document not found
     */
    404: {
        data: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        };
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2DocumentsReferenceError = PostV2DocumentsReferenceErrors[keyof PostV2DocumentsReferenceErrors];

export type PostV2DocumentsReferenceResponses = {
    /**
     * Response
     */
    200: {
        data: {
            id: number;
            type: 'invoice' | 'invoice_receipt' | 'credit_note';
            state: string;
        };
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2DocumentsReferenceResponse = PostV2DocumentsReferenceResponses[keyof PostV2DocumentsReferenceResponses];

export type GetV2TaxesData = {
    body?: never;
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path?: never;
    query?: never;
    url: '/v2/taxes';
};

export type GetV2TaxesErrors = {
    /**
     * Response
     */
    400: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2TaxesError = GetV2TaxesErrors[keyof GetV2TaxesErrors];

export type GetV2TaxesResponses = {
    /**
     * Response
     */
    200: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2TaxesResponse = GetV2TaxesResponses[keyof GetV2TaxesResponses];

export type GetV2AuthCheckData = {
    body?: never;
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path?: never;
    query?: never;
    url: '/v2/auth/check';
};

export type GetV2AuthCheckErrors = {
    /**
     * Response
     */
    400: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2AuthCheckError = GetV2AuthCheckErrors[keyof GetV2AuthCheckErrors];

export type GetV2AuthCheckResponses = {
    /**
     * Response
     */
    200: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2AuthCheckResponse = GetV2AuthCheckResponses[keyof GetV2AuthCheckResponses];

export type PostV2ChangeStateData = {
    body?: {
        type: 'invoice' | 'invoice_receipt' | 'credit_note';
        id: number | null;
        state: string;
        actualizeDateBeforeChange?: boolean;
    };
    headers: {
        'x-account-name': string;
        'x-api-key': string;
        'x-env'?: 'prod' | 'dev';
    };
    path?: never;
    query?: never;
    url: '/v2/change_state';
};

export type PostV2ChangeStateErrors = {
    /**
     * Response
     */
    400: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2ChangeStateError = PostV2ChangeStateErrors[keyof PostV2ChangeStateErrors];

export type PostV2ChangeStateResponses = {
    /**
     * Response
     */
    200: {
        data?: unknown;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type PostV2ChangeStateResponse = PostV2ChangeStateResponses[keyof PostV2ChangeStateResponses];

export type GetV2MetaErrorCodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v2/meta/error-codes';
};

export type GetV2MetaErrorCodesResponses = {
    /**
     * Response
     */
    200: {
        data: Array<{
            code: string;
            message: string;
            description: string | null;
        }>;
        success: boolean;
        error: {
            message: string | null;
            code: string;
            metadata: {
                [key: string]: unknown;
            };
        } | null;
        metadata: {
            [key: string]: unknown;
        };
    };
};

export type GetV2MetaErrorCodesResponse = GetV2MetaErrorCodesResponses[keyof GetV2MetaErrorCodesResponses];
